import { Inter } from 'next/font/google'
import './globals.css'
import Toast from './components/Toast'
import dynamic from 'next/dynamic'

const Modal = dynamic(() => import('./components/Modal'), {
  ssr: false
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-white" lang="en">
      <body className={`h-full ${inter.className}`}>
        <Toast />
        <Modal />
        {children}
      </body>
    </html>
  )
}
